HotKeySet("{ESC}", "Terminate")
$i = 0
Sleep(3000)

Func SendMsg($msg)
	send("t")
	Sleep(1000)
	send($msg)
	send("{ENTER}")
EndFunc

Func Fast($msg)
	send("t")
	Sleep(30)
	send($msg)
	send("{ENTER}")
EndFunc

SendMsg("CREEPER")
SendMsg("AWWWW MAAAN")
SendMsg("So we back in the mine")
SendMsg("got our pick axe swinging from side to side")
SendMsg("Side, side to side")
SendMsg("This task a grueling one")
SendMsg("hope to find some diamonds tonight, night, night")
SendMsg("Side, side to side")
Fast("side")
Fast("side")
Fast("side")
Fast("side side")
Fast("side")
Fast("side")
Fast("side")
Fast("side")
Fast("side")
Fast("side side")
Fast("side")
Fast("side")
Fast("side")
Fast("side")
Fast("side")
Fast("side side")
Fast("side")
Fast("side")